remover_dispositivo:
  name: Remover Dispositivo
  description: Remove um dispositivo EasyMonitor do Home Assistant.
  fields:
    device_id:
      name: ID do Dispositivo
      description: ID único do dispositivo EasyMonitor (ex EASYMON_XXXXX).
      required: true
      selector:
        text: {}