publish:
  name: "Publicar Mensagem MQTT"
  description: "Publica um comando no EasyMonitor"
  fields:
    topic:
      description: "Tópico MQTT"
      example: "easymonitor/comando"
    payload:
      description: "Dados para enviar"
      example: '{"ligar": true}'
